# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: reddit_clone_development

test:
  <<: *default
  database: reddit_clone_test

production:
  <<: *default
  database: reddit_clone_production
  username: reddit_clone
  password: <%= ENV['REDDIT_CLONE_DATABASE_PASSWORD'] %>
